@id = 1

GET {{HostAddress}}/{{ProductsPath}}/{{id}}
Accept: application/json

###

@status = active
@id1 = 1
@id2 = 2
@id3 = 4
GET {{HostAddress}}/{{ProductsPath}}/list?status={{status}}&ids={{id1}}&ids={{id2}}&ids={{id3}}
Accept: application/json

###

POST {{HostAddress}}/{{ProductsPath}}
Accept: application/json
Content-Type: application/json
{
  "link" : "https://www.jomashop.com/mido-ocean-star-39-automatic-grey-gradient-dial-watch-m026-907-11-061-00.html",
  "status": "Active"
}

###

PUT {{HostAddress}}/{{ProductsPath}}/activate/{{id}}
Accept: application/json

###

PUT {{HostAddress}}/{{ProductsPath}}/deactivate/{{id}}
Accept: application/json

###

DELETE {{HostAddress}}/{{ProductsPath}}/{{id}}
Accept: application/json